trigger:
  - main
pr:
  autoCancel: true
  branches:
    include:
      - main
  drafts: true
stages:
  - stage: Build
    displayName: Build the web application
    jobs:
      - job: Build
        displayName: Build job
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: 20.x
            displayName: Install Node.js
          - script: |
              npm install -g @angular/cli
              npm install
              ng build --configuration production
            displayName: Angular Build
  - stage: Dev
    displayName: Deploy to the dev environment
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: Deploy
        environment: dev
      - job: Build
        displayName: Deploy to Dev
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: 20.x
            displayName: Install Node.js
          - script: |
              npm install -g @angular/cli
              npm install
              ng build --configuration production
            displayName: Angular Build
  - stage: Staging
    displayName: Deploy to the staging environment
    dependsOn: Dev
    jobs:
      - deployment: Deploy
        environment: dev
      - job: Build
        displayName: Build job
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: 20.x
            displayName: Install Node.js
          - script: |
              npm install -g @angular/cli
              npm install
              ng build --configuration production
            displayName: npm install and build

